# Generated by Django 3.2.8 on 2021-10-25 10:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='profilePics/default.jpg', upload_to='profilePics'),
        ),
    ]
